### ISSUE TITLE
`mesh` instead of `sharedMesh`

### ISSUE THREAD

**Issue by TJHeuvel** [dgreenheck/OpenFracture#1]
https://github.com/dgreenheck/OpenFracture/blob/7edc606baefc54fa7938034eb638ad7cb5d015c5/Runtime/Scripts/Fracture.cs#L29

Are you sure you wanted to copy the mesh here, instead of using the shared version?

**Comment by dgreenheck** [comment]
Good catch. This code is only used for debugging, I forgot to remove it after I had fixed that particular issue.
