### ISSUE TITLE
What do I import?

### ISSUE THREAD

**Issue by heysailboat** [dgreenheck/OpenFracture#18]
I'm a beginner at Unity and I needed this for a game. I can't install it with package manager and wanted to do it the other way by downloading and importing the code manually. **What do I import?**

**Comment by vrkitten** [comment]
download the main zip file and extract it. use the package manager to import the package.json file, then click on 'Samples' in the package manager and import the demo scenes. this worked for me.

**Comment by heysailboat** [comment]
> download the main zip file and extract it. use the package manager to import the package.json file, then click on 'Samples' in the package manager and import the demo scenes. this worked for me.

how? where's the zip file?

**Comment by vrkitten** [comment]
on the homepage of the project, under the green code button

![image](https://github.com/dgreenheck/OpenFracture/assets/116233830/8c572bf1-9fcd-430c-b8ad-478ca45d1fd6)
