### ISSUE TITLE
Reference another script inside the Fracture.cs

### ISSUE THREAD

**Issue by m-dastagir** [dgreenheck/OpenFracture#3]
I am not able to add any reference to other scripts from Fracture.cs script. For example:

```
public class Fracture : MonoBehaviour
{
   public MyOtherScript otherScript;
   ///
}
```
I get the error ```The type or namespace name 'MyOtherScript' could not be found (are you missing a using directive or an assembly reference?)```
This happens if the script to be referenced is placed in another folder. Is there a way to fix this?

**Comment by jukrb0x** [comment]
the two classes are not in the same namespace, you may find  `namespace {...` at the top of your classes

try to do something like below:

assuming `MyOtherScript` is under `SomeOtherNamespace` like

```c#
namespace SomeOtherNamespace {
  public class MyOtherScript : MonoBehaviour
  {
    /// ...
  }

}

```


```c#
using SomeOtherNamespace;
// ...
public class Fracture : MonoBehaviour
{
   public MyOtherScript otherScript;
   // this should be fine
}

```
