### ISSUE TITLE
Cut face vertices doesn't perfectly match the mesh

### ISSUE THREAD

**Issue by GSoftcaze** [dgreenheck/OpenFracture#9]
Hi,

First, thanks for the package, it is really cool !

I am facing an issue, and I am in trouble to resolve it. The cut face doesn't match exactly the original mesh (see picture bellow) :

Original mesh : 
![image](https://user-images.githubusercontent.com/76959175/212487988-64cb3315-e636-4696-8694-6728c232137b.png)

Fractured mesh :
![image](https://user-images.githubusercontent.com/76959175/212487977-bc7698bf-e0c8-4dff-88bc-e022f13e55eb.png)

The main issue is that the mesh is concave, so the vertices go straight to point A to point B. Do you see a way to fix this behavior ?

Thanks in advance !

Have a nice day.

**Comment by GSoftcaze** [comment]
I finaly found a workaround,

I set the material transparent while it's frozen, then I change it to opaque as soon as it is unfrozen.

**Comment by dgreenheck** [comment]
@GSoftcaze The algorithm can handle concave meshes. The artifact you are seeing means your mesh has open or self-intersecting geometry. Please see the README for more information.
